# -*- coding: utf-8 -*-
"""Gamurot_M1-L2_DeMoivre'sTheorem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kLdBEfJriTxVzeF8LkBbTFg0dMVjAMVk

<font size="5">***Instruction*: Expand Python Modules and Functions section first then run the code below to avoid NameError when running the code in the Solutions/Code section.**</font>

#**Python Modules and Functions**
-- compiled by addgamurot
"""

import cmath
import math
from sympy import *
from sympy import pretty_print as pp 
from sympy.interactive import printing
printing.init_printing(use_latex=True)

def polar_form(comp_num):
  r = abs(comp_num)
  rad = cmath.phase(comp_num)
  angle = math.degrees(rad)
  polar_form = r, angle
  return polar_form

def rectangular_form(p_form):
  r = p_form[0]
  angle = p_form[1]
  rad_angle = math.radians(angle)
  cos_angle = math.cos(rad_angle)
  sin_angle = math.sin(rad_angle)
  x = r*cos_angle
  y = r*sin_angle
  rectangular_form = complex(x,y)
  return rectangular_form

def exponential_form(p_form):
  r = p_form[0]
  angle = math.radians(p_form[1])
  exp_form_components = r , angle
  return exp_form_components

"""# **<center>Module 1 <center/>**
# <center> **Lesson 2: De Moivre's Theorem** <center/>
Solving Problems about De Moivre's Theorem using Python.

##**2.1 Powers of Complex Numbers**

###**Problem 1.**
Determine the value of $(-7 + j5)^4$, expressing the result in polar and rectangular forms

###**Solution/Code**
"""

# given z = (-7 + j5)^4

z = -7 + 5j
new_z = pow(z,4)

a = polar_form(new_z)
b = str(a[0]) + '∠' + str(round(a[1],2) + 360) + '°'
c = rectangular_form(a)
d = complex(math.floor(c.real), math.ceil(c.imag))

# output
print("polar form: ", b )
print("rectangular form: ", d)

"""###**Conclusion/Answer** 
Therefore, the value of $(-7+j5)^4$ in polar and rectangular form is $5476\angle217.85^{\circ}$ and $(-4324-3359j)$, respectively.

##**2.2 Roots of Complex Numbers**

###**Problem 2.**
Determine the two square roots of the complex number $(5 + j12)$ in polar and cartesian forms and show the roots on an Argand diagram.

###**Solution/Code**
"""

# given z = (5 + j12)
z = 5 + 12j

a = polar_form(z)

# solution 1
# in polar form
b = round(math.sqrt(a[0]), 2) , round((a[1]/2), 2)
b1 = str(b[0]) + '∠' + str(b[1]) + '°'
print("first solution in polar form: {0} or {1} " .format(b, b1))

# in cartesian or rectangular form
c = rectangular_form(b)
c1 = round(c.real, 2), round(c.imag, 2)
c2 = complex(c1[0],c1[1])
print("first solution in cartesian form: ", c2)

# solution 2
# in polar form
d = round(math.sqrt(a[0]), 2) , round(((a[1] + 360)/2), 2)
d1 = str(d[0]) + '∠' + str(d[1]) + '°'
print("second solution in polar form: {0} or {1} " .format(d, d1))

# in cartesian or rectangular form
e = rectangular_form(d)
e1 = round(e.real, 2), round(e.imag, 2)
e2 = complex(e1[0],e1[1])
print("second solution in cartesian form: ", e2)
latex(e2)

"""###**Conclusion/Answer** 
Therefore, the two square roots of the complex number $(5 + j12)$ in polar and cartesian forms are $3.61\angle33.69^{\circ}$ and $3+2j$ , $3.61\angle213.69^{\circ}$ and $-3-2j$, respectively.

###**Problem 3.**
Find the roots of $[(5 + j3)]^{\frac{1}{2}}$ in rectangular form, correct to 4 significant figures.

###**Solution/Code**
"""

# given z = (5 + j12)
z = 5 + 3j

a = polar_form(z)

# solution 1
# in cartesian or rectangular form
b = round(math.sqrt(a[0]), 3) , round((a[1]/2),2)
c = rectangular_form(b)
c1 = round(c.real, 3), round(c.imag, 4)
c2 = complex(c1[0],c1[1])
print("first solution in cartesian form: ", c2)

# solution 2
# in cartesian or rectangular form
d = round(math.sqrt(a[0]), 3) , round(((a[1] + 360)/2),2)
e = rectangular_form(d)
e1 = round(e.real, 3), round(e.imag, 4)
e2 = complex(e1[0],e1[1])
print("second solution in cartesian form: ", e2)

"""###**Conclusion/Answer** 
Therefore, the two roots are $2.327+0.6446j$ and $-2.327-0.6646j$.

##**2.3 The Exponential Form of a Complex Number**

###**Problem 4.**
Change $(3 - j4)$ into (a) polar form, (b) exponential form.

###**Solution/Code**
"""

# given
z = 3 - 4j
# converting rec to pol
a = polar_form(z) 

# (a)
# in polar form
b = round(a[0], 2) , round(a[1], 2)
b1 = str(b[0]) + '∠' + str(b[1]) + '°'
print("in polar form: {0} or {1} " .format(b, b1))

# (b)
# in exponential form, z = re^(jθ), where θ must be in radians

def exponential_form(p_form):
  r = p_form[0]
  angle = math.radians(p_form[1])
  exp_form_components = r , angle
  return exp_form_components

c = exponential_form(a)
c1 = str(c[0]) + 'exp' + '[j' + '(' + str(round(c[1], 3)) + ')' + ']'
print("in exponential form: ", c1)

"""###**Conclusion/Answer** 
Therefore, $3-j4$ in polar and exponential form is $5\angle-53.13^{\circ}$ and $5e^{-0.927j}$.

###**Problem 5.**
Convert $7.2e^{j1.5}$ into rectangular form.

###**Solution/Code**
"""

# given 7.2exp(j1.5)
exponential_comp_r = 7.2
exponential_comp_angle = 1.5

# converting 1.5rad to deg
angle_in_deg = round(math.degrees(exponential_comp_angle), 2) 

# in polar form
p = exponential_comp_r, angle_in_deg

# converting pol to rec
r = rectangular_form(p)
r1 = complex(round(r.real, 2), round(r.imag, 2)) 
print("simplified rectangular form: ", r1)

"""###**Conclusion/Answer** 
Therefore, $7.2e^{j1.5}$ in rectangular form is $0.51+7.18j$.

###**Problem 6.**
Express $z = 2e^{1 + j\frac{\pi}{3}}$ in cartesian form.

###**Solution/Code**
"""

# given 
# z = 2exp(1+j(π/3)) = 2exp(1) x (exp(j(π/3)))
# π/3 = 60°
e = math.exp(1)
polar = 2*e , 60
# cartesian form
a = rectangular_form(polar)
a1 = complex(round(a.real, 3), round(a.imag, 3))
print("Cartesian form: ", a1)

"""###**Conclusion/Answer** 
Therefore, $z = 2e^{1 + j\frac{\pi}{3}}$ in cartesian form is $2.718+4.708j$.

###**Problem 7.**
Change $6e^{2-j3}$ into $(a + jb)$ form.

###**Solution/Code**
"""

# given 
# z = 6exp(1-j(3)) = 6exp(2) x (exp(-j(3)))
#  converting -3rad to degrees
angle_in_rad = -3
angle_in_deg = math.degrees(angle_in_rad)

e = math.exp(1)
polar = 6*(pow(e,2)) , angle_in_deg
# cartesian form
a = rectangular_form(polar)
a1 = complex(round(a.real, 2), round(a.imag, 2))
print("(a + bj) form: ", a1)

"""###**Conclusion/Answer** 
Therefore, $6e^{2-j3}$ into $(a + jb)$ form is $-43.89-6.26j$.

###**Problem 8.**
If $z = 4e^{j1.3}$, determine $ln~z~(a)~$ in cartesian form, and (b) in polar form.

###**Solution/Code**
"""

# if z = r[exp(jθ)] then ln z = ln[r(exp(jθ))]
# so ln z = ln r + jθ
# given 
r = 4
#  converting -3rad to degrees
angle_in_rad = 1.3
angle_in_deg = math.degrees(angle_in_rad)
# expressing r and angle_in_rad as a tuple
p = r, angle_in_deg
# then ln z = 4exp(j1.3) = ln 4 + j1.3
# in cartesian form
a = math.log(r) + 1.3j
a1 = complex(round(a.real, 3), round(a.imag, 3))
print("Cartesian form: ", a1)
# in polar form
b = polar_form(a1)
b1 = round(b[0], 2), round(b[1], 2)
b2 = str(b1) + ' or ' + str(b1[0]) + '∠' + str(b1[1]) + '°'
print("Polar form: ", b2)

"""###**Conclusion/Answer** 
Therefore, ln z in cartesian and polar form is $1.386+1.3j$ and $1.9\angle43.17^{\circ}$, respectively.

##**2.4 Locus Problems**

###**Problem 9.**
Determine the locus defined by $|z| = 4$, given that $z = x + jy$.

###**Solution/Code**
"""

x, y, z = symbols('x y z')
pp('Given:')

eq1 = Eq(abs(z), 4)
display(eq1)
eq2 = Eq(x + y*I, z)
display(eq2)
pp('')

pp('Solution:')
eq3 = Eq(abs(z), sqrt(x**2 + y**2))
display(eq3)
z = 4
eq4 = Eq(abs(z), sqrt(x**2 + y**2))
display(eq4)
eq5 = Eq(pow(abs(z), 2), pow(sqrt(x**2 + y**2), 2))
pp('')
eq5

"""###**Conclusion/Answer** 
Therefore, the locus defined by $|z| = 4$ is a circle with equation $x^2 + y^2 = 16$.

###**Problem 10.**
Determine the locus defined by $arg~z = \frac{\pi}{4}$, given that $z = x + yj$.

###**Solution/Code**
"""

theta, z, x, y = symbols('arg(z) z x y')
pp('Given:')
eq1 = Eq(arg(z), pi/4)
display(eq1)
eq2 = Eq(z, x + I*y)
display(eq2)
pp('')
pp('Solution:') 
pp('θ is called the arg z')
eq3 = Eq(theta, atan(y/x))
display(eq3)
pp('So in this example,\t')
eq4 = Eq(atan(y/x), pi/4)
display(eq4)
eq5 = Eq(tan(atan(y/x)),tan(pi/4))
display(eq5)
pp('Thus, if (y/x) = 1, then y = x ')

"""###**Conclusion/Answer** 
Therefore, the locus defined by $arg~z = \frac{\pi}{4}$ is a line with equation $x = y$.

###**Problem 11.**
If $z = x + jy$, determine the locus defined by $arg~(z - 1) = \frac{\pi}{6}$.

###**Solution/Code**
"""

z, y, x, theta = symbols('z y x arg(z)')
pp('Given:')
eq1 = Eq(z, x + I*y)
display(eq1)
eq2 = Eq(arg(z-1), pi/6)
display(eq2)
pp('Solution:')
display(eq2.subs(z, x + I*y))
pp('θ is called the arg z')
eq3 = Eq(theta, atan(y/x))
display(eq3)
pp('For this example,')
eq4 = Eq(atan(y/(x-1)), pi/6)
display(eq4)
pp('Solving for y, we get,')
eq5 = solve(eq4, y)
display(eq5)

"""###**Conclusion/Answer** 
Therefore, the locus defined by $arg~(z - 1) = \frac{\pi}{6}$ is a straight line with equation $y = \frac{\sqrt3(x-1)}{3}$.

###**Problem 12.**
Determine the locus defined by $|z-2| = 3$, given that $z = x + jy$.

###**Solution/Code**
"""

z, y, x, theta = symbols('z y x arg(z)')
pp('Given:')
eq1 = Eq(abs(z-2), 3)
display(eq1)
eq2 = Eq(z, x + I*y)
display(eq2)
pp('Solution:')
display(eq1.subs(z, x + I*y))
eq3 = Eq(abs(z-2), sqrt((x-2)**2 + y**2))
display(eq3)
pp('')
eq4 = Eq(abs(z-2), 3)
display(eq4)
pp('')
eq5 = Eq(3 , sqrt((x-2)**2 + y**2))
display(eq5)
eq6 = Eq(3**2, pow(sqrt((x-2)**2 + y**2), 2))
print("Squaring both sides, we get,")
display(eq6)

"""###**Conclusion/Answer** 
Therefore, the locus defined by $|z-2| = 3$ is a circle with equation $(x-2)^2 + y^2 = 9$.

###**Problem 13.**
If $z = x + jy$, determine the locus defined by $|\frac{z-1}{z+1}| = 3$.

###**Solution/Code**
"""

z, y, x = symbols('z y x')
pp('Given:')
eq1 = Eq((abs(z-1))/(abs(z+1)), 3)
display(eq1)
eq2 = Eq(z, x + I*y)
display(eq2)
pp('Solution:')
eq3 = Eq(sqrt((abs(z-1))/(abs(z+1))), 3)
display(eq3.subs(z, x + I*y))
pp('')
print("Squaring both sides, we get,")
eq4 = Eq(pow(sqrt((abs(z-1))/(abs(z+1))), 2), 3**2)
display(eq4.subs(z, x + I*y))
eq5 = (x-1)**2 + y**2
eq6 = (x+1)**2 + y**2
eq7 = Eq(3**2, pow(sqrt(eq5/eq6), 2))
pp('Simplifying,')
display(eq7)
eq8 = ((9*eq6) - eq5)/4
pp('')
simplify(eq8)
pp('')
eq9 = Eq(eq8/2, 0)
display(eq9)
pp('')
pp('we get,\n')
display(expand(eq9))
pp('\n Completing the square gives:')
eq10 = nsimplify((5/2)/2)
eq11 = nsimplify(pow((5/2)/2, 2))
eq12 = Eq((x + eq10)**2 + y**2, -1 + eq11)
display(eq12)

"""###**Conclusion/Answer** 
Therefore, the locus defined by $|\frac{z-1}{z+1}| = 3$ is a circle with equation $(x + \frac{5}{4})^2 + y^2 = \frac{9}{16}$.

#Summary
<div align="justify"><font size="3">For this module, the sympy library is used to perform symbolic or algebraic calculations  . It  is difficult not using sympy as python treats for example x and y variables as a memory location to store values where it could be an integer, a list, or a tuple, and etc. </font></div>   

---

#<center>$---$End of Module 1, Lesson 2$---$<center/>
"""